# Generated by Django 6.0.2 on 2026-03-13 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='courseArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseArea', models.CharField(max_length=25)),
                ('course', models.CharField(max_length=30)),
            ],
        ),
    ]
