# Generated by Django 6.0.2 on 2026-05-13 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp1', '0002_coursearea'),
    ]

    operations = [
        migrations.CreateModel(
            name='frameworkStandards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseAreaCode', models.CharField(max_length=4)),
                ('accreditation', models.CharField(max_length=1)),
                ('year', models.IntegerField()),
                ('frameworkStandards', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='coursearea',
            name='courseAreaCode',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='coursearea',
            name='courseArea',
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name='unitData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accreditation', models.CharField(max_length=1)),
                ('unitName', models.CharField(max_length=50)),
                ('unitValue', models.FloatField()),
                ('unitGoals', models.TextField()),
                ('unitDesc', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp1.coursearea')),
            ],
        ),
    ]
