# Generated by Django 6.0.2 on 2026-03-18 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp1', '0002_coursearea'),
    ]

    operations = [
        migrations.CreateModel(
            name='courseDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseDesc', models.CharField(max_length=50)),
            ],
        ),
    ]
